# === Help ===
help: ## Show this help message
	@echo "🚀 Fiet Protocol - Solidity Development Commands"
	@echo "================================================"
	@echo ""
	@echo "📋 Available Commands:"
	@echo ""
	@echo "🔧 Development Commands:"
	@echo "  dev                    - Complete development setup (deploy tokens, contracts, create market)"
	@echo "  build                  - Build all Solidity contracts"
	@echo "  fork                   - Start Anvil fork for local development"
	@echo ""
	@echo "🚀 Deployment Commands:"
	@echo "  deploy-tokenA          - Deploy USDT mock token"
	@echo "  deploy-tokenB          - Deploy USDC mock token"
	@echo "  deploy                 - Deploy all core contracts"
	@echo "  read-deployment        - Read deployment information"
	@echo ""
	@echo "📊 Market Operations:"
	@echo "  create-market          - Create a new market"
	@echo "  pause-market           - Pause market operations"
	@echo "  add-liquidity          - Add liquidity to market"
	@echo "  remove-liquidity       - Remove liquidity from market"
	@echo "  swap                   - Execute a swap"
	@echo ""
	@echo "🔍 Quality & Security:"
	@echo "  install-deps           - Install project dependencies"
	@echo "  lint                   - Run linting checks"
	@echo "  lint-fix               - Fix linting issues"
	@echo "  format                 - Format code"
	@echo "  format-check           - Check code formatting"
	@echo "  security               - Run security analysis"
	@echo "  quality                - Run all quality checks (format, lint, security)"
	@echo ""
	@echo "🧪 Experiments Commands:"
	@echo "  exp                    - Show available experiments commands"
	@echo "  exp <command>          - Run experiments command (e.g., exp wrap-eth-sepolia)"
	@echo ""
	@echo "⚙️  Configuration:"
	@echo "  MODE=LOCAL|REMOTE      - Set deployment mode (default: LOCAL)"
	@echo "  NETWORK=sepolia|arbitrum - Set target network (default: sepolia)"
	@echo ""
	@echo "💡 Examples:"
	@echo "  make help               - Show this help message"
	@echo "  make dev                - Complete development setup"
	@echo "  make fork               - Start local fork"
	@echo "  make NETWORK=arbitrum deploy - Deploy to Arbitrum mainnet"
	@echo "  make MODE=REMOTE deploy - Deploy to remote network"
	@echo "  make exp                - Show experiments commands"
	@echo "  make exp wrap-eth-sepolia - Wrap ETH on Arbitrum Sepolia"
	@echo "  make exp create-market-sepolia - Create market on Arbitrum Sepolia"
	@echo ""
	@echo "📖 For more information, see the documentation in docs/"