/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVRLManager  {
    function initialize(address liquidity_verifier, address delta_manager, address uniswap_hook, uint256 decimals) external;

    function depositVerifiedFiat(address owner, bytes32 currency_hash, uint256 amount) external;

    function getUserCurrencyVrl(address owner, bytes32 currency_hash) external view returns (uint256);

    function lockVrl(address owner, bytes32 currency_hash, uint256 delta) external returns (uint256);

    function unlockVrl(address owner, bytes32 currency_hash, uint256 delta) external returns (uint256);

    function burnVrlForDelta(address owner, bytes32 currency_hash, uint256 delta) external returns (uint256);

    function offramp(address custodian, bytes32 currency_hash, uint256 delta) external;

    function getDecimals() external view returns (uint256);

    function getOwner() external view returns (address);

    function getLockedVrl() external view returns (uint256);
}
