[profile.default]
src = "src"
script = "script"
out = "out"
libs = ["../../contracts/evm/lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./out" },
]

remappings = [
  "forge-std/=../../contracts/evm/lib/forge-std/src/",
  "@uniswap/v4-core/=../../contracts/evm/lib/v4-periphery/lib/v4-core/",
]
