/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IDeltaManager  {
    function initialize(address liquidity_verifier, address stake_contract, address vrl_manager, address settlement_manager) external;

    function whitelistCustodian(address custodian, bool whitelist) external;

    function registerAsCustodian(bytes32 currency_hash) external;

    function registerAsLp(bytes32 currency_hash) external;

    function unregisterParticipant() external;

    function signalDelta(address owner, bytes32 currency_hash, int256 delta) external returns (int256);

    function deltaOfParticipant(address owner) external view returns (int256);

    function currencyHashOfParticipant(address owner) external returns (bytes32);

    function isActiveParticipant(address owner) external returns (bool);

    function getCurrencyParticipants(bytes32 currency_hash) external returns (address[] memory);

    function getCurrencySignalledParticipants(bytes32 currency_hash) external returns (address[] memory);

    function adminSettleDelta(uint256 amount, address user) external;

    function userSettleDelta(uint256 amount) external;

    function deltaToVrl(uint256 amount) external;
}
