/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IFietStake  {
    function initialize(address stake_token, address delta_manager, address settlement_manager, uint256 min_stake) external;

    function setAdmin(address new_admin_address, bool is_admin) external;

    function getAdmin(address admin_address) external returns (bool);

    function stake(uint256 amount) external;

    function stakeFor(address owner, uint256 amount) external;

    function delegateStake(address new_delegatee) external;

    function removeStakeDelegate() external;

    function getEffectiveAccount(address owner) external view returns (address);

    function unstake(uint256 amount) external;

    function slash(address owner, uint256 bps) external;

    function slashByAmount(address owner, uint256 target_amount, uint64 slash_factor) external;

    function withdraw(uint256 amount, address to) external;

    function getBalance(address owner) external returns (uint256);

    function getStakedToken() external returns (address);

    function getMinStake() external view returns (uint256);

    function isStaked(address owner) external returns (bool);

    function getSlashBps(address owner, uint256 target_amount, uint64 slash_factor) external returns (uint256);

    function getSlashAmount(uint256 bps) external view returns (uint256);
}
