/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ILiquidityManager  {
    function initialize(address vrl_manager_address, address delta_manager_address) external;

    function manualSignalDeposit(address owner, address custodian, string calldata currency, uint256 amount) external;

    function manualSignalLiquidity(address lp_address, string calldata currency, uint256 amount) external;
}
