/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ISettlement  {
    function initialize(address delta_manager, address stake_manager, uint64 ttl) external;

    function createRequestForSettlement(uint256 settle_amount) external;

    function bid(uint64 rfs_id, uint256 amount) external;

    function settle(uint64 rfs_id) external;

    function closeRequestForSettlement() external;

    function hoursElapsedSince(uint64 start_timestamp) external view returns (uint64);

    function getActiveRfs(address owner) external view returns (uint64);
}
