// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.26;

import {LCCFactoryLinkedLib} from "../../../src/libraries/LCCFactoryLib.sol";
import {LiquidityHubLinkedLib} from "../../../src/libraries/LiquidityHubLinkedLib.sol";
import {VTSCommitLib} from "../../../src/libraries/VTSCommitLib.sol";
import {VTSPositionLib} from "../../../src/libraries/VTSPositionLib.sol";
import {VTSLifecycleLinkedLib} from "../../../src/libraries/VTSLifecycleLinkedLib.sol";
import {VTSPositionMMOpsLib} from "../../../src/libraries/VTSPositionMMOpsLib.sol";

/// @notice CREATE2 deploy helpers for Echidna harnesses at addresses matching the Foundry linker map.
/// @dev Linker addresses come from `FOUNDRY_PROFILE=echidna` with `FOUNDRY_CONFIG=.echidna-gen/foundry.toml`
///      (generated by `scripts/echidna_prepare_linked_libs.py` before Echidna runs). Deployed code must match
///      `predicted*()` for the current linked `type(Lib).creationCode`.
library EchidnaLinkedLibs {
    /// @dev Must match harness etch target (Echidna default deployer).
    address internal constant ECHIDNA_DEPLOYER = 0x00a329c0648769A73afAc7F9381E08FB43dBEA72;

    error VTSLifecycleLinkedLibAddrMismatch();
    error VTSPositionMMOpsLibAddrMismatch();
    error LCCFactoryLinkedLibAddrMismatch();
    error LiquidityHubLinkedLibAddrMismatch();
    error VTSCommitLibAddrMismatch();
    error VTSPositionLibAddrMismatch();
    error DeployFailed();

    function deployLCCFactoryLinkedLib() internal {
        address lib = _deploy(keccak256("echidna.LCCFactoryLinkedLib"), type(LCCFactoryLinkedLib).creationCode);
        if (lib != predictedLCCFactoryLinkedLib()) revert LCCFactoryLinkedLibAddrMismatch();
    }

    function deployLiquidityHubLinkedLib() internal {
        address lib = _deploy(keccak256("echidna.LiquidityHubLinkedLib"), type(LiquidityHubLinkedLib).creationCode);
        if (lib != predictedLiquidityHubLinkedLib()) revert LiquidityHubLinkedLibAddrMismatch();
    }

    function deployVTSCommitLib() internal {
        address lib = _deploy(keccak256("echidna.VTSCommitLib"), type(VTSCommitLib).creationCode);
        if (lib != predictedVTSCommitLib()) revert VTSCommitLibAddrMismatch();
    }

    function deployVTSPositionLib() internal {
        address lib = _deploy(keccak256("echidna.VTSPositionLib"), type(VTSPositionLib).creationCode);
        if (lib != predictedVTSPositionLib()) revert VTSPositionLibAddrMismatch();
    }

    function deployVTSLifecycleLinkedLib() internal {
        address lib = _deploy(keccak256("echidna.VTSLifecycleLinkedLib"), type(VTSLifecycleLinkedLib).creationCode);
        if (lib != predictedVTSLifecycleLinkedLib()) revert VTSLifecycleLinkedLibAddrMismatch();
    }

    function deployVTSPositionMMOpsLib() internal {
        address lib = _deploy(keccak256("echidna.VTSPositionMMOpsLib"), type(VTSPositionMMOpsLib).creationCode);
        if (lib != predictedVTSPositionMMOpsLib()) revert VTSPositionMMOpsLibAddrMismatch();
    }

    // --- CREATE2 address prediction (same initCode + salt as deploy*; single source for scripts) ---

    function predictedLCCFactoryLinkedLib() internal pure returns (address) {
        return _predictCreate2(keccak256("echidna.LCCFactoryLinkedLib"), type(LCCFactoryLinkedLib).creationCode);
    }

    function predictedLiquidityHubLinkedLib() internal pure returns (address) {
        return _predictCreate2(keccak256("echidna.LiquidityHubLinkedLib"), type(LiquidityHubLinkedLib).creationCode);
    }

    function predictedVTSCommitLib() internal pure returns (address) {
        return _predictCreate2(keccak256("echidna.VTSCommitLib"), type(VTSCommitLib).creationCode);
    }

    function predictedVTSPositionLib() internal pure returns (address) {
        return _predictCreate2(keccak256("echidna.VTSPositionLib"), type(VTSPositionLib).creationCode);
    }

    function predictedVTSLifecycleLinkedLib() internal pure returns (address) {
        return _predictCreate2(keccak256("echidna.VTSLifecycleLinkedLib"), type(VTSLifecycleLinkedLib).creationCode);
    }

    function predictedVTSPositionMMOpsLib() internal pure returns (address) {
        return _predictCreate2(keccak256("echidna.VTSPositionMMOpsLib"), type(VTSPositionMMOpsLib).creationCode);
    }

    function _predictCreate2(bytes32 salt, bytes memory initCode) private pure returns (address) {
        bytes32 initCodeHash = keccak256(initCode);
        bytes32 digest = keccak256(abi.encodePacked(bytes1(0xff), ECHIDNA_DEPLOYER, salt, initCodeHash));
        return address(uint160(uint256(digest)));
    }

    function _deploy(bytes32 salt, bytes memory initCode) private returns (address lib) {
        assembly {
            lib := create2(0, add(initCode, 0x20), mload(initCode), salt)
        }
        if (lib == address(0)) revert DeployFailed();
    }
}
