name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  solidity:
    name: Solidity Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version
        working-directory: solidity

      - name: Run Forge fmt
        run: forge fmt --check
        working-directory: solidity
        id: fmt

      - name: Run Forge build
        run: forge build --sizes
        working-directory: solidity
        id: build

      - name: Run Forge tests
        run: forge test -vvv
        working-directory: solidity
        id: test

  stylus:
    name: Stylus Tests
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable

        - name: Run tests for staking contract
          run: cargo test --lib
          working-directory: stylus/fiet_stake

        - name: Run tests for liquidity verifier
          run: cargo test --lib
          working-directory: stylus/liquidity_verifier

        - name: Run tests for FI$T Token
          run: cargo test --lib
          working-directory: stylus/token

        - name: Run tests for VRL Manager
          run: cargo test --lib
          working-directory: stylus/vrl_manager